services:
  untivitti-frontend:
    image: ghcr.io/ammiratafabiano/untivitti-frontend:latest
    container_name: untivitti-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  untivitti-backend:
    image: ghcr.io/ammiratafabiano/untivitti-backend:latest
    container_name: untivitti-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3442:3442"
    environment:
      - PORT=3442
      - ALLOWED_ORIGINS=https://untivitti.ammiratafabiano.dev,http://localhost:8100
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
