services:
  untivitti-frontend:
    image: ghcr.io/ammiratafabiano/untivitti-frontend:main
    container_name: untivitti-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  untivitti-server:
    image: ghcr.io/ammiratafabiano/untivitti-server:main
    container_name: untivitti-server
    restart: unless-stopped
    ports:
      - "3442:3442"
    environment:
      - PORT=3442
      - ALLOWED_ORIGINS=https://untivitti.ammiratafabiano.dev,http://localhost:8100
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
